### ISSUE TITLE
modelling relations between arbitrary regions or fixed region

### ISSUE THREAD

**Issue by qiulesun** [facebookresearch/GloRe#1]
As shown in Fig. 1, this work  mainly aims at capturing relations between arbitrary regions over the full input space. However, in Eq. 1, the node in interaction space seems to represent the fixed region (a.k,a original feature map) in coordinate space rather than arbitrary regions.

**Comment by cypw** [comment]
In Eq. 1, the feature vector (v_i) for each node is generated by a weighted global pooling, where the weight is b_i. Since b_i is actually the i-th output feature map of a convolution layer, the weight value is not fixed and is activated at the locations/regions where specific content/concept/object/part is detected. You can understand b_i as a soft mask or a saliency map.

**Comment by qiulesun** [comment]
@cypw  In Fig. 7, you show the weights for four projection maps. I hold the view that it it very meaningful and helpful for understanding the proposed method. Could you provide more details about how to implement it or share the code to implement it?
