### ISSUE TITLE
Video accuracy of kinetics.

### ISSUE THREAD

**Issue by bupt-wcm** [facebookresearch/GloRe#4]
Thanks for the great job. 
The github code only contains clip accuracy, so I wonder how to get the video accuracy? 
And the resutls reported in the github is about 1% higher than that in paper, is there any modification?

**Comment by cypw** [comment]
Hi WangCMing,

I did not re-train the model and code is the same, but I do get slightly higher clip accuracy on "Res101 (3D) + Ours" during evaluation as you noticed.  Since I still use the same code and params, I guess the higher accuracy benefits from the newer version of OS,  CUDA, and CuDNN, but I am also not sure.

Best,
Yunpeng

**Comment by bupt-wcm** [comment]
Thanks for your reply! And can you give me some information on how to get video accuracy? Actually, I have been struggling for a long time about it.

**Comment by cypw** [comment]
You can get the video level accuracy by setting `num_clips = 10` and `num_crops = 5` in [test-single-clip.py](https://github.com/facebookresearch/GloRe/blob/master/test/test-single-clip.py#L111), and replace the [`transforms.CenterCrop`](https://github.com/facebookresearch/GloRe/blob/master/test/test-single-clip.py#L125) with [`transforms.MixedCrop`](https://github.com/facebookresearch/GloRe/blob/master/data/image_transforms.py#L244).
