### ISSUE TITLE
What is epoch_div_factor?

### ISSUE THREAD

**Issue by bupt-wcm** [facebookresearch/GloRe#6]
Thanks for your work and code.
I run your code recently, and find the variable 'epoch_div_factor' in train_model.py. And it makes the lr cannot be decayed normally as the setting in the args 'lr_steps'. So I wonder what the 'epoch_div_factor' is used for.

**Comment by cypw** [comment]
The `epoch_div_factor` is the stride of each iteration, it is useful for distributed training and should be related to the number of workers, see [here](https://github.com/facebookresearch/GloRe/blob/c9ad998fb7b207bd29625e8b210adea3e2e5667c/train/model.py#L222)

I was using 8 workers (i.e. nodes), and thus the number of iter of each epoch should be reduced by a factor of 8 (i.e. `epoch_div_factor=8`). But I force it to be 4 just in case it saves the model too frequently. In my case, change `epoch_div_factor` won't affect the `lr` as the `lr` is computed by #iter rather than epochs. You can change [it](https://github.com/facebookresearch/GloRe/blob/c9ad998fb7b207bd29625e8b210adea3e2e5667c/train_model.py#L26) back as [here](https://github.com/facebookresearch/GloRe/blob/c9ad998fb7b207bd29625e8b210adea3e2e5667c/train/model.py#L222) to fix it.

Thank you!
